project:
  type: website
  output-dir: docs
  resources: 
    - "assets/resources/cv_correndoadrian_dec2024.pdf"

website:
  title: "Adrian Correndo"
  navbar:
    background: "#bc4749"
    left:
      - href: 01-index.qmd
        text: Home
      - href: 02-career.qmd
        text: Career
      - href: 03-publications.qmd
        text: Publications
      - href: 04-digital.qmd
        text: Digital Resources
      - href: 05-talks.qmd
        text: Talks
      - href: 06-contact.qmd
        text: Contact
    right:
      - icon: github
        href: https://github.com/adriancorrendo/
      - icon: twitter
        href: https://twitter.com/aacorrendo
      - icon: linkedin
        href: https://www.linkedin.com/in/adriancorrendo/
      - icon: google
        href: http://bit.ly/3zpaXCo
  page-footer: 
    left: "<span> Developed by Adrian Correndo using [Quarto](https://quarto.org/). License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/). </span>"
    background: dark
  twitter-card:
    creator: "@aacorrendo"
    
format:
  html:
    theme: 
      light: journal
      dark: darkly
    css: styles.css
    toc: true
    toc-title: ""
    toc-location: left
    code-copy: true
    code-overflow: wrap
    mainfont: "Atkinson Hyperlegible"

editor: visual

