project:
  type: website
  output-dir: docs

website:
  title: "AdrianCorrendo"
  navbar:
    background: "#4a4e69"
    left:
      - href: 01-index.qmd
        text: Home
      - href: 02-career.qmd
        text: Career
      - href: 03-publications.qmd
        text: Publications
      - href: 04-digitalops.qmd
        text: DigitalOps
      - href: 05-contact.qmd
        text: Contact
    right:
      - icon: github
        href: https://github.com/adriancorrendo/
      - icon: twitter
        href: https://twitter.com/aacorrendo
      - icon: linkedin
        href: https://www.linkedin.com/in/adriancorrendo/
      - icon: globe
        href: https://correndo1.wixsite.com/main
  page-footer: 
    left: "<span> Developed by Adrian Correndo using [Quarto](https://quarto.org/). License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/). </span>"
    background: light
  twitter-card:
    creator: "@aacorrendo"
    
format:
  html:
    theme: unite
    css: styles.css
    toc: true
    toc-title: ""
    toc-location: left
    code-copy: true
    code-overflow: wrap
    mainfont: "Atkinson Hyperlegible"

editor: visual

