---
title: "Adrian Correndo"
---

Welcome to my website!

# About me

::: panel-tabset
## 🙋🏻Bio

I was born in 1987 and raised up in Buenos Aires, Argentina. I'm married to Milagros, and we are parents of Amelie. Since a child, I developed a huge curiosity about nature, particularly biology and weather, which undoubtedly influenced my career decision. Agronomy was the perfect fit for my interests. I got my Bachelor's at the University of Buenos Aires, where I also obtained my Master in Soil Sciences while working in research and extension for the Southern Cone Program of the International Plant Nutrition Institute (IPNI). I proudly obtained my Ph.D. degree in Agronomy at Kansas State University. Cropping systems, with focus on soil fertility and crop nutrition, and data science are my passion and expertise within the vast agronomy-world.

## 🎓Education

-   Ph.D., Agronomy. Kansas State University. 2021.

-   MS, Soil Science. Universidad de Buenos Aires. 2018.

-   BS, Agronomy. Universidad de Buenos Aires. 2011.

# 
:::

# 👁️‍🗨️Vision

I am an agronomist with +10 years of experience in research and stakeholders education, underpinning the development and recommendation of the best crop management practices for productive, efficient, and environmentally safe farming systems. My passion and expertise are in cropping systems, soil fertility and crop nutrition, with a strong component of modern data analytics for the advancement of agriculture. I aim to play an active role in transdisciplinary projects that gather diverse agricultural stakeholders.

# 🌽Interests

Sustainable Farming \| Crop Nutrition \| Predictive Ag \| Digital Solutions

A great crop hides a whole story of questions underneath. Curiosity drives farmers, agronomists, and scientists to achieve improvements in our farming systems and communities.

-   Research

    -   Dynamic future scenarios require research exploring the interactions between plant genetics (G), environment (E), and crop management (M).

-   Extension

    -   By addressing stakeholders' concerns we visualize research gaps, we facilitate the right development and adoption of technologies, and we also enhance productivity and the resources use efficiency.

-   Education

    -   Leaders of the farming of the future require transdisciplinary work and education that provides them the tools to efficiently utilize multiple data sources for decision-making.

# 📑Publications

-   Secchi, M.A., **Correndo, A.A.**, Stamm, M., Durrett , T., Vara Prasad, P.V., Messina, C., and Ciampitti , I.A., 202#. Suitability of different environments for winter canola oil production in the United States of America. Field Crops Res. In-press.

-   **Correndo, A.A.**, McArtor, B., Prestholt, A., Hernandez, C., Kyveryga, P., and Ciampitti , I.A., 2022. Interactive Soybean Variable-Rate Seeding Simulator for Farmers. Agron. J. In-press. https://doi.org/10.1002/agj2.21181

-   Sadras, V.O., Giordano, N., **Correndo, A.A.**, Cossani, M., Ferreyra, J.M., Caviglia, O.P., Coulter, J.A., Ciampitti , I.A., and Lollato,R.A., 2022. Temperature-driven developmental modulati on of yield response to nitrogen in wheat and maize. Frontiers in Agronomy. https://doi.org/10.3389/fagro.2022.903340

-   **Correndo, A.A.**, Adee, E., Moro Rosso, L.H., Tremblay, N., Vara Prasad, P.V., Du, J., and Ciampitti, I.A., 2022. Footprints of corn nitrogen management on the following soybean crop. *Agron. J.* 1-14. https://doi.org/10.1002/agj2.21023

-   **Correndo, A.A.**, Tremblay, N., ...Ciampitti, I.A. et al., 2021. Unraveling uncertainty drivers of the maize yield response to nitrogen: A Bayesian and machine learning approach. *Agr. For. Meteorol.* 311, 108668. https://doi.org/10.1016/j.agrformet.2021.108668

-   **Correndo, A.A.**, Gutierrez-Boem, F.H., Garcia, F.O.,... Salvagiotti, F., 2021. Attainable yield and soil texture as drivers of maize response to nitrogen: a synthesis analysis for Argentina. *Field Crops Res.* 273, 108299. https://doi.org/10.1016/j.fcr.2021.108299

-   **Correndo, A.A.**, Fernandez, J., Prasad, V., Ciampitti, I.A., 2021. Do water and nitrogen management practices impact grain quality in maize? *Agronomy* 11(9), 1851. https://doi.org/10.3390/agronomy11091851

-   Ciampitti, I.A., de Borja Reis, A.F., Cordova, C., Castellano, M.J., Archontoulis, S., **Correndo, A.A.**, Antunes de Almeida, L.F., Moro Rosso, L.H.,, 202X. Revisiting biological nitrogen fixation dynamics in soybeans. *Front. Plant Sci.* 12, 727021. https://doi.org/10.3389/fpls.2021.727021

-   Moro Rosso, L.H., de Borja Reis, A.F., **Correndo, A.A.**, Ciampitti, I.A., 2021. XPolaris: an R-package to retrieve United States soil data at 30-meter resolution. *BMC Res Notes* 14, 327. https://doi.org/10.1186/s13104-021-05729-y

-   **Correndo, A.A.**, Hefley, T., Holzworth, D., Ciampitti, I.A., 2021. Revisiting linear regression to test agreement in continuous predicted-observed datasets. *Agr. Syst.* 192, 103194. https://doi.org/10.1016/j.agsy.2021.103194

-   **Correndo, A.A.**, Moro Rosso, L.H., Ciampitti, I.A., 2021. Retrieving and processing agro-meteorological from API-client sources using R software. *BMC Res. Notes* 14, 205. https://doi.org/10.1186/s13104-021-05622-8

-   **Correndo, A.A.**, Rubio, G., Garcia, F.O., Ciampitti, I.A., 2021. Subsoil-potassium depletion accounts for the nutrient budget in high-potassium agricultural soils. *Sci. Rep.* 11, 11597. https://doi.org/10.1038/s41598-021-90297-1

-   **Correndo, A.A.**, Rotundo, J.L., Tremblay, N., et al., 2021. Assessing the uncertainty of maize yield with no nitrogen fertilization. *Field Crops Res.* 260, 107985. https://doi.org/10.1016/j.fcr.2020.107985

-   Appelhans, S.C., Carciochi, W.D., **Correndo, A.A.**, et al. 2021. Predicting soil test phosphorus decrease in non‐P‐fertilized conditions. *Eur. J. Soil Sci.* 2021; 1-- 11. https://doi.org/10.1111/ejss.12946

-   **Correndo, A.A.**, Salvagiotti, F., García, F.O., Gutiérrez Boem, F.H., 2017. A modification of the arcsine-log calibration curve for analysing soil test value-relative yield relationships. *Crop and Pasture Science* 68 (3): 297-304. https://doi.org/10.1071/CP16444

-   Barbieri, P.A., Sainz Rozas, H.R. Wyngaard, N., Eyherabide, M., Reussi Calvo, N.I., Salvagotti, F., **Correndo, A.A.**, et al., 2017. Can Edaphic Variables Improve DTPA-Based Zinc Diagnosis in Corn?. *Soil Sci. Soc. Am. J.* 81, 556-563. https://doi.org/10.2136/sssaj2016.09.0316

-   **Correndo, A.A.**, Boxler, M., García, F.O., 2015. Economic analysis of fertilization management with focus on the long term. *Ci. Suelo* 33(2), 197-212. http://www.suelos.org.ar/publicaciones/vol_33n2/v33n2a04.pdf

# 🖼️Images

Coming soon...
